services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: kanari
      DB_USER: kanari_user
      DB_PASSWORD: kanari_pass
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: kanari
      PG_USER: kanari_user
      PG_PASSWORD: kanari_pass
      S3_ACCESS_KEY: _
      S3_SECRET_KEY: _
      S3_ENDPOINT: _
    depends_on:
      - db
      - postgres

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: kanari
      MYSQL_USER: kanari_user
      MYSQL_PASSWORD: kanari_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./sql/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kanari
      POSTGRES_USER: kanari_user
      POSTGRES_PASSWORD: kanari_pass
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
  pg-data:
