name: CI

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check compilation with `python -m`
        run: python -m your_flask_module_name
        continue-on-error: true  # Avoid failure if app runs instead of exiting

      - name: Run Flask app in background
        run: |
          export FLASK_APP=your_flask_module_name
          flask run --host=127.0.0.1 --port=5000 &
          echo $! > flask.pid
          sleep 5

      - name: Test timeout returns 504
        run: |
          set -e
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 4 http://127.0.0.1:5000/your_timeout_endpoint)
          if [ "$STATUS_CODE" -ne 504 ]; then
            echo "Expected 504, got $STATUS_CODE"
            exit 1
          fi

      - name: Stop Flask app
        run: |
          kill $(cat flask.pid) || true
