name: CI
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]
env:
  NO_COLOR: "1"
  PYTHONPYCACHEPREFIX: "/home/runner/.cache/python"
  PYTHONUTF8: "1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb-dev libpq-dev curl
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Python compilation
        run: |
          find . -name "*.py" -type f -exec python -m py_compile {} +
        continue-on-error: true
      - name: Run Flask app in background (no services configured)
        run: |
          python -m flask --app wsgi.py run --port=5000 &
          echo $! > flask.pid
          sleep 5
      - name: Test app works without services configured
        run: |
          set -e
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 4 http://127.0.0.1:5000/)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Expected 200 (no services configured), got $STATUS_CODE"
            exit 1
          fi
      - name: Stop Flask app
        run: |
          if [ -f flask.pid ]; then
            kill "$(cat flask.pid)" || true
            sleep 2
          fi
      - name: Test MySQL timeout returns 504
        env:
          DB_HOST: "10.255.255.1"  # RFC1918 non-routed address - will timeout
          DB_PORT: "3306"
          DB_NAME: "test"
          DB_USER: "test"
          DB_PASSWORD: "test"
        run: |
          python -m flask --app wsgi.py run --port=5001 &
          echo $! > flask_mysql_timeout.pid
          sleep 5
          set -e
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://127.0.0.1:5001/)
          if [ "$STATUS_CODE" -ne 504 ]; then
            echo "Expected 504 (MySQL timeout), got $STATUS_CODE"
            exit 1
          fi
          if [ -f flask_mysql_timeout.pid ]; then
            kill "$(cat flask_mysql_timeout.pid)" || true
            sleep 2
          fi
      - name: Test PostgreSQL timeout returns 504
        env:
          PG_HOST: "10.255.255.2"  # RFC1918 non-routed address - will timeout
          PG_PORT: "5432"
          PG_DATABASE: "test"
          PG_USER: "test"
          PG_PASSWORD: "test"
        run: |
          python -m flask --app wsgi.py run --port=5002 &
          echo $! > flask_pg_timeout.pid
          sleep 5
          set -e
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://127.0.0.1:5002/)
          if [ "$STATUS_CODE" -ne 504 ]; then
            echo "Expected 504 (PostgreSQL timeout), got $STATUS_CODE"
            exit 1
          fi
          if [ -f flask_pg_timeout.pid ]; then
            kill "$(cat flask_pg_timeout.pid)" || true
            sleep 2
          fi
      - name: Test S3 timeout returns 504
        env:
          S3_ACCESS_KEY: "test_key"
          S3_SECRET_KEY: "test_secret"
          S3_ENDPOINT: "http://10.255.255.3:9000"  # Unreachable S3 endpoint
          S3_BUCKET: "test-bucket"
        run: |
          python -m flask --app wsgi.py run --port=5003 &
          echo $! > flask_s3_timeout.pid
          sleep 5
          set -e
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://127.0.0.1:5003/)
          if [ "$STATUS_CODE" -ne 504 ]; then
            echo "Expected 504 (S3 timeout), got $STATUS_CODE"
            exit 1
          fi
          if [ -f flask_s3_timeout.pid ]; then
            kill "$(cat flask_s3_timeout.pid)" || true
          fi
